# TODO modify hoge
version: '2'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: rails_vuex_chat_development
      MYSQL_ROOT_PASSWORD: fasjkdlw29
      MYSQL_USER: rails_vuex_chat_project
      MYSQL_PASSWORD: fasjkdl29
    volumes:
      - "./docker/mysql/config:/etc/mysql/conf.d"
    ports:
      - "3306:3306" # ホストからゲストへポートフォワード
  web:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    command: ./bin/bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      REDIS_URL: redis://redis:6379/0
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
      - "3035:3035"
    volumes:
      - .:/workdir # ソースコード変更したらDocker側も即反映されるように
    links:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379